services:
  - type: web
    name: my-node-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    branch: main
    repo: https://github.com/username/my-node-app
    envVars:
      - key: NODE_ENV
        value: production

